# Generated by Django 4.0.6 on 2023-06-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ingreso_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='motivo',
            field=models.CharField(max_length=50),
        ),
    ]
